language: cpp

compiler:
  - clang
  - gcc

script:
  - git submodule add https://github.com/google/googletest.git thirdparty/googletest 
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. && make
